<?php
/**
 * Implements hook_permission().
 */
function sitenameconf_permission() {
  return array(
    'access myconf' => array(
      'title' => t('Administer permission for sitenameconf'),
      'description' => t('Administer permission for sitenameconf'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function sitenameconf_menu() {
  $items['myconf'] = array(
    'title' => 'Sitename config',
    'description' => 'My sitename configuration form',
    'page callback' => 'drupal_get_form',
	'page arguments' => array('sitenameconf_form'),
	'access arguments' => array('access myconf'),
    'menu_name' => 'main-menu',
    'type' => MENU_NORMAL_ITEM,
   );
   
  return $items;
}

function sitenameconf_form($form, &$form_state){
  $form = array();
  
  $form['sitename'] = array(
    '#type' => 'textfield',
    '#title' => t('Site name'),
    '#default_value' => variable_get('site_name', "Default site name"),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save')
  );
  
  return $form;
}

function sitenameconf_form_submit($form, &$form_state){
  variable_set('site_name', $form_state['values']['sitename']);
  drupal_set_message(t('Site name has been saved.'));
}
